//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QURAANEY.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QURAANEY.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Dashboard CurrencyCulture=&quot;ar-SY&quot;&gt;
        ///  &lt;Title Text=&quot;Dashboard&quot; /&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;SqlDataSource Name=&quot;SQL Data Source 1&quot; ComponentName=&quot;dashboardSqlDataSource1&quot;&gt;
        ///      &lt;Connection Name=&quot;Connection&quot; ConnectionString=&quot;data source=.;initial catalog=MY_QURAAN;integrated security=True&quot; /&gt;
        ///      &lt;Query Type=&quot;SelectQuery&quot; Name=&quot;V_COUNT_RATES&quot;&gt;
        ///        &lt;Tables&gt;
        ///          &lt;Table Name=&quot;V_COUNT_RATES&quot; X=&quot;30&quot; Y=&quot;30&quot; Width=&quot;125&quot; Height=&quot;102&quot; /&gt;
        ///        &lt;/Tables&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dash_quranney {
            get {
                return ResourceManager.GetString("dash_quranney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Dashboard CurrencyCulture=&quot;ar-SY&quot;&gt;
        ///  &lt;Title Text=&quot;Dashboard&quot; /&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;SqlDataSource Name=&quot;SQL Data Source 1&quot; ComponentName=&quot;dashboardSqlDataSource1&quot;&gt;
        ///      &lt;Connection Name=&quot;localhost_MY_QURAAN_Connection&quot; ProviderKey=&quot;MSSqlServer&quot;&gt;
        ///        &lt;Parameters&gt;
        ///          &lt;Parameter Name=&quot;server&quot; Value=&quot;ISRAA-PC&quot; /&gt;
        ///          &lt;Parameter Name=&quot;database&quot; Value=&quot;MY_QURAAN&quot; /&gt;
        ///          &lt;Parameter Name=&quot;useIntegratedSecurity&quot; Value=&quot;True&quot; /&gt;
        ///          &lt;Par [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dash_test {
            get {
                return ResourceManager.GetString("dash_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tashkeel {
            get {
                object obj = ResourceManager.GetObject("tashkeel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
